### ISSUE TITLE
Remove /Change mobs (provisional)

### ISSUE THREAD

**Issue by vadis365** [vadis365/TheErebus#504]
Remove and replace Leech with something else.
Remove Swamp Wisp.
Change Blood Snail to a different name and give it a purpose.
Add Cockroach.
Add Spider eggs.
Add back Firebrats as a spawn when Gneiss is broken.
Add Sand Flies to desert biomes and remove Botflies from desert biomes.

**Comment by DylanGK** [comment]
Closing this issue due to old age.
